version: "3.5"

services :
  webapp4:
       container_name: ${WEBAPP_4_NAME}
       build:
         context: ./webapp
         dockerfile: Dockerfile
       networks:
         heig:
           ipv4_address: ${WEBAPP_4_IP}
       ports:
         - "4003:3000"
       environment:
            - TAG=${WEBAPP_4_NAME}
            - SERVER_IP=${WEBAPP_4_IP}
  webapp5:
       container_name: ${WEBAPP_5_NAME}
       build:
         context: ./webapp
         dockerfile: Dockerfile
       networks:
         heig:
           ipv4_address: ${WEBAPP_5_IP}
       ports:
         - "4004:3000"
       environment:
            - TAG=${WEBAPP_5_NAME}
            - SERVER_IP=${WEBAPP_5_IP}
  haproxy:
       container_name: ha
       build:
         context: ./ha
         dockerfile: Dockerfile
       ports:
         - 80:80
         - 1936:1936
         - 9999:9999
       expose:
         - 80
         - 1936
         - 9999
       networks:
         heig:
           ipv4_address: ${HA_PROXY_IP}
       environment:
            - WEBAPP_4_IP=${WEBAPP_4_IP}
            - WEBAPP_5_IP=${WEBAPP_5_IP}
networks:
    heig:
        name: heig
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}
